services:
  api:
    build:
      context: ../
      dockerfile: infra/Dockerfile
    container_name: symfony-api
    networks:
      - api_network
    volumes:
      - ../reconhecimentoFacialApi:/var/www/html
    environment:
      APP_ENV: prod
      DATABASE_URL: mysql://root:root@mysql:3306/symfonydb  # Alterado para usar porta interna do MySQL
      DATABASE_URL_POSTGRES: pgsql://symfony_postgres:secret@postgres:5432/symfonydb  # Alterado para usar porta interna do PostgreSQL
      CORS_ALLOW_ORIGIN: "*"

    expose:
      - 9000

    depends_on:
      - mysql
      - postgres

    command: [ "wait-for-it", "mysql:3306", "-t", "30", "--", "wait-for-it", "postgres:5432", "-t", "30", "--", "php-fpm" ]

    
  nginx:
    image: nginx:latest
    container_name: nginx-api
    ports:
      - "8080:80"
    networks:
      - api_network

    volumes:
      - ../infra/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../reconhecimentoFacialApi:/var/www/html
    depends_on:
      - api

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfonydb
    networks:
      - api_network
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3310:3306"

  postgres:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: symfony_postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: symfonydb
    networks:
      - api_network
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5442:5432" # Porta padrão para PostgreSQL

  redis:
    image: redis:6.2
    container_name: redis
    networks:
      - api_network
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  postgres_data:
  redis_data:


networks:
  api_network:
    driver: bridge
